import { useState, useRef, useEffect } from 'react';
import type { ClipboardEvent, KeyboardEvent } from 'react';
import {
  Box, TextField, Button, Typography, Link as MuiLink,
  ToggleButtonGroup, ToggleButton, Dialog, IconButton,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import QrCodeScannerIcon from '@mui/icons-material/QrCodeScanner';
import { useNavigate, Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Scanner } from '@yudiel/react-qr-scanner';
import AppToolBar from '../../components/AppToolBar';
import PinDialog from '../../components/PinDialog';
import ErrorSnackbar from '../../components/ErrorSnackbar';
import { WalletsHelper, PinCodeHelper, Wallet } from '../../lib/storage';
import { MnemonicHelper, PrivateKeyHelper } from '../../lib/mnemonic';
import heroLoginLarge from '../../assets/heroimage_login_large.png';

const IMPORTED_WALLET_NAME = 'Imported';
const MNEMONIC_LENGTH = 12;
// How many BIP44 indices to try, starting at 0, when a pasted private key might belong to
// a recovery phrase already stored on this device. Comfortably covers normal usage without
// making the "no match" case (an unrelated private key) noticeably slow.
const MNEMONIC_SEARCH_RANGE = 100;

type ImportMode = 'mnemonic' | 'privatekey';

export default function WalletLoginImport() {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [mode, setMode] = useState<ImportMode>('mnemonic');
  const [words, setWords] = useState<string[]>(Array(MNEMONIC_LENGTH).fill(''));
  const [privateKey, setPrivateKey] = useState('');
  const [showPinDialog, setShowPinDialog] = useState(false);
  const [pinMode, setPinMode] = useState<'check' | 'register'>('check');
  // Second, automatic PIN prompt shown right after the imported wallet is created and made
  // active - see the comment above showSymbolCheckPinDialog's <PinDialog> below for why this
  // step exists separately from the PIN entry above.
  const [showSymbolCheckPinDialog, setShowSymbolCheckPinDialog] = useState(false);
  const [showScanner, setShowScanner] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  // Wallets already on this device that hold a recovery phrase - whether that phrase was
  // typed/scanned into this LOGIN screen, or auto-generated by "Create New Wallet". Either
  // way, the phrase already lives on the device, so there's no need to ask for the full
  // 12-word phrase again here - "Create New Wallet" already handles deriving further
  // accounts from it - so this screen narrows down to private-key-only.
  const [mnemonicWallets, setMnemonicWallets] = useState<Wallet[] | null>(null);
  const wordRefs = useRef<(HTMLInputElement | null)[]>([]);

  useEffect(() => {
    (async () => {
      const wallets = await WalletsHelper.gets();
      const matches = wallets.filter((w) => w.hasMnemonic());
      setMnemonicWallets(matches);
      if (matches.length > 0) {
        setMode('privatekey');
      }
    })();
  }, []);

  // Still loading the wallet list - default to the full (mnemonic-capable) UI to avoid a
  // flash of the wrong layout, it'll settle within one render if a match exists.
  const hasStoredMnemonic = (mnemonicWallets?.length ?? 0) > 0;

  // The single "key" the rest of the flow (validation, wallet creation) works with,
  // derived from whichever mode is currently active.
  const key = mode === 'mnemonic' ? words.join(' ').trim() : privateKey.trim();
  const looksLikeMnemonic = mode === 'mnemonic';
  const isValidInput = key.length === 0
    ? false
    : looksLikeMnemonic ? MnemonicHelper.isValid(key) : PrivateKeyHelper.isValid(key);

  const switchMode = (newMode: ImportMode) => {
    setMode(newMode);
    setErrorMessage('');
  };

  // If a private key matches one of the BIP44 accounts derivable from a recovery phrase
  // already stored on this device, returns that phrase (so the new wallet gets stored
  // properly linked to it, just like an account added via "Create New Wallet") - otherwise
  // null, meaning the key should be stored as a standalone private-key import.
  const findMatchingMnemonic = async (normalizedPrivateKey: string, pinCode: string): Promise<string | null> => {
    if (!mnemonicWallets) {
      return null;
    }
    for (const wallet of mnemonicWallets) {
      const phrase = await wallet.decryptMnemonic(pinCode);
      if (phrase == null || !MnemonicHelper.isValid(phrase)) {
        continue;
      }
      for (let index = 0; index < MNEMONIC_SEARCH_RANGE; index++) {
        const account = MnemonicHelper.accountFromMnemonic(phrase, index);
        if (account.privateKey.toLowerCase() === normalizedPrivateKey.toLowerCase()) {
          return phrase;
        }
      }
    }
    return null;
  };

  // Distributes a run of whitespace-separated words across the 12 boxes, starting at
  // startIndex. Used both for typing a space/enter to move on, and for pasting a full
  // phrase into any one of the boxes.
  const distributeWords = (tokens: string[], startIndex: number) => {
    setWords((prev) => {
      const next = [...prev];
      tokens.forEach((word, i) => {
        if (startIndex + i < MNEMONIC_LENGTH) {
          next[startIndex + i] = word;
        }
      });
      return next;
    });
    const lastIndex = Math.min(startIndex + tokens.length, MNEMONIC_LENGTH - 1);
    wordRefs.current[lastIndex]?.focus();
  };

  const onWordChange = (index: number, value: string) => {
    if (/\s/.test(value)) {
      const tokens = value.split(/\s+/).filter((w) => w.length > 0);
      distributeWords(tokens, index);
      return;
    }
    setWords((prev) => {
      const next = [...prev];
      next[index] = value;
      return next;
    });
  };

  const onWordKeyDown = (index: number, e: KeyboardEvent<HTMLDivElement>) => {
    if (e.key === 'Enter' && index < MNEMONIC_LENGTH - 1) {
      e.preventDefault();
      wordRefs.current[index + 1]?.focus();
    } else if (e.key === 'Backspace' && words[index] === '' && index > 0) {
      e.preventDefault();
      wordRefs.current[index - 1]?.focus();
    }
  };

  const onWordPaste = (index: number, e: ClipboardEvent<HTMLDivElement>) => {
    const pasted = e.clipboardData.getData('text');
    if (/\s/.test(pasted.trim())) {
      e.preventDefault();
      distributeWords(pasted.trim().split(/\s+/), index);
    }
  };

  const onDecodeQr = (decoded: string) => {
    const trimmed = decoded.trim();
    const tokens = trimmed.split(/\s+/).filter((w) => w.length > 0);
    // In private-key-only mode (a recovery phrase is already on this device) there's no
    // mnemonic UI to switch into, so a scanned phrase is simply treated as invalid input
    // rather than silently reopening the 12-word entry the toggle was removed to avoid.
    if (tokens.length >= MNEMONIC_LENGTH && !hasStoredMnemonic) {
      setMode('mnemonic');
      setWords(tokens.slice(0, MNEMONIC_LENGTH));
    } else {
      setMode('privatekey');
      setPrivateKey(trimmed);
    }
    setShowScanner(false);
  };

  const createWalletWithPin = async (pinCode: string) => {
    try {
      if (looksLikeMnemonic) {
        if (!MnemonicHelper.isValid(key)) {
          throw new Error('invalid mnemonic');
        }
        const account = MnemonicHelper.accountFromMnemonic(key, 0);
        const wallet = await WalletsHelper.createWithMnemonic(
          IMPORTED_WALLET_NAME, account.address, account.publicKey, account.privateKey,
          MnemonicHelper.normalize(key), pinCode
        );
        await WalletsHelper.add(wallet);
        await WalletsHelper.setActive(wallet.id);
      } else {
        if (!PrivateKeyHelper.isValid(key)) {
          throw new Error('invalid private key');
        }
        const account = PrivateKeyHelper.accountFromPrivateKey(key);
        // If this key turns out to be one of the accounts of a recovery phrase already
        // imported on this device, link the new wallet to that phrase (same shape as an
        // account added via "Create New Wallet") instead of storing it as a bare key.
        const matchingPhrase = await findMatchingMnemonic(account.privateKey, pinCode);
        const wallet = matchingPhrase
          ? await WalletsHelper.createWithMnemonic(
              IMPORTED_WALLET_NAME, account.address, account.publicKey, account.privateKey, matchingPhrase, pinCode
            )
          : await WalletsHelper.createWithKeys(
              IMPORTED_WALLET_NAME, account.address, account.publicKey, account.privateKey, pinCode
            );
        await WalletsHelper.add(wallet);
        await WalletsHelper.setActive(wallet.id);
      }
      // The PIN dialog just used above (mode="check"/"register") derives the Symbol
      // account for whichever wallet was active *at that moment* - which is still the
      // previous wallet (or none, on a first-ever import), since this wallet isn't made
      // active until the two setActive() calls above, right after that dialog already
      // closed. So Symbol is never unlocked for a freshly imported wallet unless something
      // checks the PIN again now that this wallet actually is active - hence this second,
      // automatic "Check PIN" step before moving on.
      setShowSymbolCheckPinDialog(true);
    } catch {
      setErrorMessage(t('wallet.invalid_key'));
    }
  };

  const createWallet = async () => {
    // No PIN protecting this device yet - force setting one now (mode="register") rather
    // than silently falling back to encrypting the imported key/phrase with a fixed
    // default PIN. If a PIN already exists, just confirm it (mode="check") and reuse it.
    setPinMode((await PinCodeHelper.hasSavedCode()) ? 'check' : 'register');
    setShowPinDialog(true);
  };

  return (
    <div>
      <AppToolBar back="/wallet/creation/type" title={t('wallet.import_title')} />
      <Box component="img" src={heroLoginLarge} sx={{ width: '100%' }} />
      <Box sx={{ px: 2 }}>
        <Typography align="center" sx={{ mx: 2 }}>
          {(
            t(hasStoredMnemonic ? 'wallet.import_message_privatekey_only' : 'wallet.import_message', { returnObjects: true }) as string[]
          ).map((line, i) => (
            <span key={i}>{line}<br /></span>
          ))}
        </Typography>

        {!hasStoredMnemonic && (
          <Box sx={{ display: 'flex', justifyContent: 'center', mb: 2 }}>
            <ToggleButtonGroup
              value={mode}
              exclusive
              onChange={(_, newMode) => newMode && switchMode(newMode)}
              size="small"
            >
              <ToggleButton value="mnemonic">{t('wallet.import_mode_mnemonic')}</ToggleButton>
              <ToggleButton value="privatekey">{t('wallet.import_mode_privatekey')}</ToggleButton>
            </ToggleButtonGroup>
          </Box>
        )}

        {mode === 'mnemonic' ? (
          <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 1, mx: 1 }}>
            {words.map((word, i) => (
              <TextField
                key={i}
                inputRef={(el) => { wordRefs.current[i] = el; }}
                label={t('wallet.import_mnemonic_word_label', { index: i + 1 })}
                value={word}
                onChange={(e) => onWordChange(i, e.target.value)}
                onKeyDown={(e) => onWordKeyDown(i, e)}
                onPaste={(e) => onWordPaste(i, e)}
                size="small"
                slotProps={{ input: { autoCapitalize: 'off', autoCorrect: 'off', spellCheck: false } }}
              />
            ))}
          </Box>
        ) : (
          <Box sx={{ display: 'flex', alignItems: 'center', mx: '12.5%' }}>
            <TextField
              id="key"
              label={t('wallet.import_input_label_privatekey')}
              value={privateKey}
              onChange={(e) => setPrivateKey(e.target.value)}
              fullWidth
            />
          </Box>
        )}

        <Box sx={{ display: 'flex', justifyContent: 'center', mt: 1.5 }}>
          <Button startIcon={<QrCodeScannerIcon />} onClick={() => setShowScanner(true)}>
            {t('wallet.import_scan_qr')}
          </Button>
        </Box>

        {key.length > 0 && !isValidInput && (
          <Typography align="center" sx={{ color: 'error.main', fontSize: 12 }}>{t('wallet.invalid_key')}</Typography>
        )}

        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', mt: 2 }}>
          <Button variant="contained" color="primary" disabled={!isValidInput} onClick={createWallet}>OK</Button>
        </Box>

        <Typography align="center" variant="caption" sx={{ display: 'block', mt: 4 }}>
          {t('common.privacy_policy_caution')}<br />
          <MuiLink component={Link} to="/" underline="always">{t('common.privacy_policy')}</MuiLink>
        </Typography>
      </Box>

      <PinDialog open={showPinDialog} mode={pinMode} onClose={() => setShowPinDialog(false)} onPass={createWalletWithPin} />
      <PinDialog
        open={showSymbolCheckPinDialog}
        mode="check"
        onClose={() => setShowSymbolCheckPinDialog(false)}
        // A correct PIN here (checked against the wallet that's now active - see the
        // comment in createWalletWithPin above) makes PinDialog derive and cache this
        // wallet's Symbol account before we move on.
        onPass={() => navigate('/wallet/login/name')}
        // Getting Symbol working isn't required to finish importing the wallet itself -
        // if the person cancels here, let them through anyway. Symbol just stays locked
        // for this wallet until they check the PIN again from the Symbol tab.
        onCancel={() => navigate('/wallet/login/name')}
      />
      <ErrorSnackbar message={errorMessage} onClose={() => setErrorMessage('')} />

      <Dialog fullScreen open={showScanner} onClose={() => setShowScanner(false)}>
        <Box sx={{ position: 'relative', height: '100%', bgcolor: 'black' }}>
          <IconButton
            onClick={() => setShowScanner(false)}
            sx={{ position: 'absolute', top: 8, right: 8, zIndex: 1, color: 'white' }}
          >
            <CloseIcon />
          </IconButton>
          <Typography align="center" sx={{ color: 'white', position: 'absolute', top: 12, left: 0, right: 0, zIndex: 1 }}>
            {t('wallet.import_scan_title')}
          </Typography>
          {showScanner && (
            <Scanner
              onScan={(results) => { if (results[0]) onDecodeQr(results[0].rawValue); }}
              onError={(error) => setErrorMessage(error instanceof Error ? error.message : String(error))}
            />
          )}
        </Box>
      </Dialog>
    </div>
  );
}
